
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

namespace HelloWorld.Resources.Languages {

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by a text template.
    // To add or remove a member, edit your .ResX file.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18nMenu : global::Localization.ICultural, global::System.ComponentModel.INotifyPropertyChanged {

        private static readonly global::System.Lazy<I18nMenu> LazyInstance = new global::System.Lazy<I18nMenu>(() => new I18nMenu());

        /// <summary>
        ///   Instance of this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static I18nMenu Instance => LazyInstance.Value;
        
        #nullable enable
        public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        private void OnResourceCultureChanged()
        {
            this.PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(null));
        }
        
        /// <summary>
        ///   Returns ResourceManager instance.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Resources.ResourceManager ResourceManager { get; private set; }
        
        #nullable enable
        private global::System.Globalization.CultureInfo? ResourceCulture;

        /// <summary>
        ///   Returns Culture instance or null.
        /// </summary>
        #nullable enable
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Globalization.CultureInfo? Culture
        {
            get
            {
                return this.ResourceCulture;
            }
            set
            {
                if (this.ResourceCulture == value)
                {
                    return;
                }
                this.ResourceCulture = value;
                this.OnResourceCultureChanged();
            }
        }
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        private I18nMenu() {
            //this.ResourceManager = new global::System.Resources.ResourceManager("HelloWorld.Resources.Languages.I18nMenu", typeof(I18nMenu).Assembly);
            this.ResourceManager = new global::Localization.ResourceManagerX("HelloWorld.Resources.resources.dll", "HelloWorld.Resources.Languages.I18nMenu", typeof(I18nMenu));
            ((global::Localization.ICulturalManager) global::System.Windows.Application.Current).AddCultural(this);
        }

        public string this[string key]
        {
            get
            {
                return this.ResourceManager.GetString(key, this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Console"
        /// </summary>
        public string Console
        {
            get
            {
                return this.ResourceManager.GetString("Console", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Copyright"
        /// </summary>
        public string Copyright
        {
            get
            {
                return this.ResourceManager.GetString("Copyright", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Delete"
        /// </summary>
        public string Delete
        {
            get
            {
                return this.ResourceManager.GetString("Delete", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Edit"
        /// </summary>
        public string Edit
        {
            get
            {
                return this.ResourceManager.GetString("Edit", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Exit"
        /// </summary>
        public string Exit
        {
            get
            {
                return this.ResourceManager.GetString("Exit", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Export"
        /// </summary>
        public string Export
        {
            get
            {
                return this.ResourceManager.GetString("Export", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "File"
        /// </summary>
        public string File
        {
            get
            {
                return this.ResourceManager.GetString("File", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Guide"
        /// </summary>
        public string Guide
        {
            get
            {
                return this.ResourceManager.GetString("Guide", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Help"
        /// </summary>
        public string Help
        {
            get
            {
                return this.ResourceManager.GetString("Help", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Import"
        /// </summary>
        public string Import
        {
            get
            {
                return this.ResourceManager.GetString("Import", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "IP Broadcast"
        /// </summary>
        public string IP_Broadcast
        {
            get
            {
                return this.ResourceManager.GetString("IP Broadcast", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Language/Locale"
        /// </summary>
        public string Language_Or_Locale
        {
            get
            {
                return this.ResourceManager.GetString("Language Or Locale", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Logs"
        /// </summary>
        public string Logs
        {
            get
            {
                return this.ResourceManager.GetString("Logs", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Modify"
        /// </summary>
        public string Modify
        {
            get
            {
                return this.ResourceManager.GetString("Modify", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "New"
        /// </summary>
        public string New
        {
            get
            {
                return this.ResourceManager.GetString("New", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Options"
        /// </summary>
        public string Options
        {
            get
            {
                return this.ResourceManager.GetString("Options", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Preference"
        /// </summary>
        public string Preference
        {
            get
            {
                return this.ResourceManager.GetString("Preference", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Source Code"
        /// </summary>
        public string Source_Code
        {
            get
            {
                return this.ResourceManager.GetString("Source Code", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tools"
        /// </summary>
        public string Tools
        {
            get
            {
                return this.ResourceManager.GetString("Tools", this.Culture) ?? string.Empty;
            }
        }
    }

}
