
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

namespace HelloWorld.Resources.Languages {

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by a text template.
    // To add or remove a member, edit your .ResX file.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18nServerWindow : global::Localization.ICultural, global::System.ComponentModel.INotifyPropertyChanged {

        private static readonly global::System.Lazy<I18nServerWindow> LazyInstance = new global::System.Lazy<I18nServerWindow>(() => new I18nServerWindow());

        /// <summary>
        ///   Instance of this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static I18nServerWindow Instance => LazyInstance.Value;
        
        #nullable enable
        public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        private void OnResourceCultureChanged()
        {
            this.PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(null));
        }
        
        /// <summary>
        ///   Returns ResourceManager instance.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Resources.ResourceManager ResourceManager { get; private set; }
        
        #nullable enable
        private global::System.Globalization.CultureInfo? ResourceCulture;

        /// <summary>
        ///   Returns Culture instance or null.
        /// </summary>
        #nullable enable
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Globalization.CultureInfo? Culture
        {
            get
            {
                return this.ResourceCulture;
            }
            set
            {
                if (this.ResourceCulture == value)
                {
                    return;
                }
                this.ResourceCulture = value;
                this.OnResourceCultureChanged();
            }
        }
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        private I18nServerWindow() {
            //this.ResourceManager = new global::System.Resources.ResourceManager("HelloWorld.Resources.Languages.I18nServerWindow", typeof(I18nServerWindow).Assembly);
            this.ResourceManager = new global::Localization.ResourceManagerX("HelloWorld.Resources.resources.dll", "HelloWorld.Resources.Languages.I18nServerWindow", typeof(I18nServerWindow));
            ((global::Localization.ICulturalManager) global::System.Windows.Application.Current).AddCultural(this);
        }

        public string this[string key]
        {
            get
            {
                return this.ResourceManager.GetString(key, this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Adapter"
        /// </summary>
        public string Adapter
        {
            get
            {
                return this.ResourceManager.GetString("Adapter", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Cancel"
        /// </summary>
        public string Cancel
        {
            get
            {
                return this.ResourceManager.GetString("Cancel", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Driver"
        /// </summary>
        public string Driver
        {
            get
            {
                return this.ResourceManager.GetString("Driver", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Extra Options"
        /// </summary>
        public string Extra_Options
        {
            get
            {
                return this.ResourceManager.GetString("Extra Options", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Hostname"
        /// </summary>
        public string Hostname
        {
            get
            {
                return this.ResourceManager.GetString("Hostname", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name"
        /// </summary>
        public string Name
        {
            get
            {
                return this.ResourceManager.GetString("Name", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Options"
        /// </summary>
        public string Options
        {
            get
            {
                return this.ResourceManager.GetString("Options", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password"
        /// </summary>
        public string Password
        {
            get
            {
                return this.ResourceManager.GetString("Password", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Port"
        /// </summary>
        public string Port
        {
            get
            {
                return this.ResourceManager.GetString("Port", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Save"
        /// </summary>
        public string Save
        {
            get
            {
                return this.ResourceManager.GetString("Save", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Server"
        /// </summary>
        public string Server
        {
            get
            {
                return this.ResourceManager.GetString("Server", this.Culture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Username"
        /// </summary>
        public string Username
        {
            get
            {
                return this.ResourceManager.GetString("Username", this.Culture) ?? string.Empty;
            }
        }
    }

}
